# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: tests
    steps:
      - script: echo Test suit started!
        displayName: 'Starting tests...'
      - script: npm install --legacy-peer-deps 
        displayName: 'Installing dependencies...'
      - script:  npm run test
        displayName: 'Running tests...'

  - job: version_control
    dependsOn: tests
    steps:
      - script: echo Version updated!