# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: RUN_REAL_EXECUTION
    value: true
  - name: RUN_SC_INTEGRATION_TESTS
    value: false

jobs:
  - job: tests
    steps:
      - script: echo Test suit started!
        displayName: 'Starting tests...'
        
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Use Node 20'

      - script: npm install --legacy-peer-deps
        displayName: 'Installing dependencies...'

      - script: npm run build
        displayName: 'Building internal dependencies...'

      - script: mkdir -p .tmp
        displayName: 'Prepare tmp directory'

      - script: npm run test
        displayName: 'Running tests...'
        env:
          WEB3AUTH_CLIENT_ID: $(WEB3AUTH_CLIENT_ID)
          INFURA_API_KEY: $(INFURA_API_KEY)
          ALCHEMY_API_KEY: $(ALCHEMY_API_KEY)
          TEST_PRIVATE_KEY: $(TEST_PRIVATE_KEY)
          LIFI_API_KEY: $(LIFI_API_KEY)
          RUN_REAL_EXECUTION: $(RUN_REAL_EXECUTION)
          RUN_SC_INTEGRATION_TESTS: $(RUN_SC_INTEGRATION_TESTS)

          TMPDIR: $(Build.SourcesDirectory)/.tmp
          TMP: $(Build.SourcesDirectory)/.tmp
          TEMP: $(Build.SourcesDirectory)/.tmp

  - job: version_control
    dependsOn: tests
    steps:
      - script: npm run version -- wallet --minor
        displayName: 'Version Updated.'
        