pipelines:
  custom:
    test-adapter:
      - step:
          name: Testing Adapter
          script:
            - export ADAPTER_NAME=${BITBUCKET_BRANCH#github/}
            - echo "Validating GitHub adapter: $ADAPTER_NAME"
            - npm ci
            - npm run build
            - npm run tests
            - echo "Running tests for $ADAPTER_NAME"
          artifacts:
            - tests/test-results/**

  branches:
     'github/*':
      - step:
          name: Validate GitHub Adapter
          script:
            - export ADAPTER_NAME=${BITBUCKET_BRANCH#github/}
            - npm ci
            - npm run build
            - npm run tests