pipelines:
  custom:
    integration-test-adapter:
      - step:
          name: Integration Test Adapter
          script:
            - export ADAPTER_NAME=${BITBUCKET_BRANCH#github/}
            - echo "Running integration tests for adapter: $ADAPTER_NAME"
            - npm ci
            - npm run build
            - npm run build:integration
            - npm run test:integration
          artifacts:
            - tests/test-results/**

  branches:
    'github/*':
      - step:
          name: Validate GitHub Adapter
          script:
            - export ADAPTER_NAME=${BITBUCKET_BRANCH#github/}
            - echo "Validating GitHub adapter: $ADAPTER_NAME"
            - npm ci
            - npm run build
            - npm run test:wallet
            - echo "To run integration tests manually, go to Bitbucket > Pipelines > Run pipeline > integration-test-adapter"